### ISSUE TITLE
Deploy multiple "identical" systems on the same AWS zone shown some problems 

### ISSUE THREAD

**Issue by Nss** [nearform/nscale-compiler#22]
Me and @mcollina first noticed this problem while trying to deploy a system with multiple topologies to AWS. 

Unfortunately the containers of the systems generated from the compile have all the same ids and, given the fact that those ids are used as name for AWS objects (instances/elb/autoscaligGroups) that have as requirement that the name has to be unique, the deploy was failing.

The problem is that the hash that follows the container name doesn't include the first level name of the topology:

Hash generation
===============

Given this configuration:

```
topology = {
  'webElb': [
    {
      'webSg': [
        {
          'machine': [
            'web'
          ]
        }
      ]
    }
  ]
};

exports.topology={
  'aws': topology,
  'local': topology
};
```

The hash generation is done using the paths:

```
['webElb']
['webElb', 'webSg']
['webElb', 'webSg', 'machine']
['webElb', 'webSg', 'machine', 'web']
```
This means that the `aws` topology will have the same hashes of the `local` topology with all the consequences reported above.

The solution is to include the `aws` and `local` keys in the hash generation:

e.i.

```
['aws', 'webElb']
['aws', 'webElb', 'webSg'] 
```

This will generate unique hashes for different topologies/systems

**Comment by Nss** [comment]
__ATTENTION__: This may cause problems with already deployed systems. @mcollina am I right?

**Comment by mcollina** [comment]
This is sure to cause problems with deployed systems, in particular those with resources already deployed, e.g. AWS instances, ELBs and security groups. On upgrade, all those will be destroyed and recreated.

Possible solution:
1. we help people with an upgrade path
2. we put this behind a configuration flag in `config.js`

I'm in for this behing an opt-in, disable (and retrocompatible) by default.
I still consider running _everything_ on a single region (where AWS names would clash) a bad practice.

@pelger what's your opinion on this?

**Comment by dberesford** [comment]
+1 on getting this in, it's really important for delivery this week. IMO we're ok to break things at this stage in the nscale development, but let's do breaking changes in a proper semver fashion.

**Comment by pelger** [comment]
Agreed - OK to break and provide an upgrade path
